---
- name: Koski deployment
  hosts: tor_backends
  sudo: true
  serial: 1
  vars:
    koski_home: /srv/tomcat/koski
    koski_user: tomcat
    koski_deploy_dir: "{{ koski_home }}/deploy"
  tasks:
  - name: Copy koski application package
    copy: src={{ koski_package }} dest=/tmp/{{ koski_package | basename }}
  - name: Remove old application package
    file: path={{ koski_deploy_dir }} state=absent
  - name: Create application directory
    file: path={{ koski_deploy_dir }} state=directory
  - name: Unpack koski application package
    unarchive:
      copy=no
      src=/tmp/{{ koski_package | basename }}
      dest={{ koski_deploy_dir }}
      group={{ koski_user }}
      owner={{ koski_user }}
    notify: restart koski
  - meta: flush_handlers # force restart before running application responding task
  - name: Check for application responding
    uri:
      url: "http://127.0.0.1:8080/koski/buildversion.txt"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 1

  handlers:
    - name: restart koski
      service: name=koski state=restarted
