---
- name: Koski deployment
  hosts: tor_backends
  sudo: true
  vars:
    koski_home: /srv/tomcat/koski
    koski_user: tomcat
    koski_deploy_dir: "{{ koski_home }}/deploy"
  tasks:
  - name: Copy koski application package
    copy: src={{ koski_package }} dest=/tmp/{{ koski_package | basename }}
  - name: Remove old application package
    file: path={{ koski_deploy_dir }} state=absent
  - name: Create application directory
    file: path={{ koski_deploy_dir }} state=directory
  - name: Unpack koski application package
    unarchive:
      copy=no
      src=/tmp/{{ koski_package | basename }}
      dest={{ koski_deploy_dir }}
      group={{ koski_user }}
      owner={{ koski_user }}
    notify: restart koski
  handlers:
    - name: restart koski
      service: name=koski state=restarted
